#ifndef		__CTUSB_RAMMAP_H__
#define		__CTUSB_RAMMAP_H__
                        
#define USB_DESC_DATA_BASE          0x0000
#define USB_DESC_DATA_BASE_LEN      0x0480
#define USB_DESC_DATA_ADDR          (USB_DESC_DATA_BASE)
#define USB_DESC_DATA_ADDR_LEN      (USB_DESC_DATA_BASE_LEN)

#define USB_ENTITY_DATA_BASE        0x0480
#define USB_ENTITY_DATA_BASE_LEN    0x015C
#define USB_ENTITY_DATA_ADDR_LEN    (USB_ENTITY_DATA_BASE_LEN)

#define USB_HIDIN_DATA_BASE         (USB_ENTITY_DATA_BASE+USB_ENTITY_DATA_BASE_LEN)
#define USB_HIDIN_DATA_BASE_LEN     0x0004
#define USB_HIDIN_DATA_ADDR_LEN     (USB_HIDIN_DATA_BASE_LEN)

#define USB_BULKIN_DATA_BASE        0x05E0
#define USB_BULKIN_DATA_BASE_LEN    0x0400
#define USB_BULKIN_DATA_BASE_END    (USB_BULKIN_DATA_BASE+USB_BULKIN_DATA_BASE_LEN-1)
#define USB_BULKIN_DATA_ADDR_LEN    (USB_BULKIN_DATA_BASE_LEN)

#define USB_BULKOUT_DATA_BASE       0x09E0
#define USB_BULKOUT_DATA_BASE_LEN   0x0120
#define USB_BULKOUT_DATA_BASE_END   (USB_BULKOUT_DATA_BASE+USB_BULKOUT_DATA_BASE_LEN-1)
#define USB_BULKOUT_DATA_ADDR_LEN   (USB_BULKOUT_DATA_BASE_LEN)

#define USB_VENDER_DATA_BASE        0x0F00
#define USB_VENDER_DATA_BASE_LEN    0x0100
#define USB_VENDER_DATA_ADDR_LEN    (USB_VENDER_DATA_BASE_LEN)



#define USB_MEM_START               ((unsigned char volatile xdata *) 0x0000)

#endif  //__CTUSB_RAMMAP_H__